version: '3.9'

services:

  attendance-api:

    build: .

    container_name: attendance-api

    ports:
      - "8000:8000"

    volumes:
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs

    restart: unless-stopped